import discord
from discord.ext import commands
import random
# Create the bot instance
intents = discord.Intents.default()
bot = commands.Bot(command_prefix="y", intents=intents)

@bot.event
async def on_ready():
    # Set bot to invisible
    await bot.change_presence(status=discord.Status.invisible)
    print(f"Logged in as {bot.user} - Invisible mode enabled.")

#COMPLEMENT COMMAND

@bot.tree.command(name="compliment", description="Send someone a compliment!")
async def compliment(interaction: discord.Interaction, user: discord.User):
    # List of compliments
    compliments = [
    "**You're an awesome person!**",
    "**You have a great sense of humor.**",
    "**You're incredibly talented!**",
    "**You light up the room!**",
    "**You're one in a million!**",
    "**You bring out the best in others.**",
    "**You're so thoughtful!**",
    "**You're a true friend.**",
    "**Your smile is contagious.**",
    "**You're amazing just the way you are.**",
    "**You always know how to brighten my day.**",
    "**You're a great listener.**",
    "**You're a rockstar!**",
    "**You have such a kind heart.**",
    "**You make the world a better place.**",
    "**You're a ray of sunshine.**",
    "**You're so creative!**",
    "**Your positive energy is uplifting.**",
    "**You have a wonderful personality.**",
    "**You're a great problem solver.**",
    "**You're so inspiring!**",
    "**You're full of amazing ideas.**",
    "**You always know just what to say.**",
    "**Your confidence is contagious.**",
    "**You're a natural leader.**",
    "**You have such a warm presence.**",
    "**You're so easy to talk to.**",
    "**You're like a breath of fresh air.**",
    "**You're one of a kind!**",
    "**Your creativity knows no bounds.**",
    "**You're so thoughtful and considerate.**",
    "**You have such a beautiful soul.**",
    "**You're incredibly strong.**",
    "**You make every day brighter.**",
    "**You always know how to make people feel better.**",
    "**You're a truly special person.**",
    "**You're always so full of energy.**",
    "**You have such a great sense of style.**",
    "**You're a great teammate.**",
    "**You're so caring and understanding.**",
    "**You have an amazing work ethic.**",
    "**You're a joy to be around.**",
    "**You're incredibly intelligent!**",
    "**You're such a genuine person.**",
    "**You always make people feel welcome.**",
    "**You're so strong and resilient.**",
    "**You're one of the kindest people I know.**",
    "**You're always so encouraging.**",
    "**You bring out the best in everyone.**",
    "**You have such a beautiful spirit.**",
    "**You make everything so much fun.**",
    "**You're so thoughtful and giving.**",
    "**You're a true inspiration!**",
    "**You have such a calm and peaceful energy.**",
    "**You're so good at what you do.**",
    "**You always put others first.**",
    "**You're so wise beyond your years.**",
    "**You make people feel valued and loved.**",
    "**You're a great motivator.**",
    "**You always brighten up the room.**",
    "**You have a heart of gold.**",
    "**You're so compassionate.**",
    "**You're such a great role model.**",
    "**You always go above and beyond.**",
    "**You're incredibly generous.**",
    "**You always know how to make people laugh.**",
    "**You're so easygoing and fun to be around.**",
    "**You're a true blessing to everyone around you.**",
    "**You're so unique and special.**",
    "**You're so brave and courageous.**",
    "**You're such a great communicator.**",
    "**You always stay calm under pressure.**",
    "**You're incredibly passionate.**",
    "**You have a beautiful mind.**",
    "**You have an amazing sense of adventure.**",
    "**You're a true go-getter.**",
    "**You're so talented at everything you do.**",
    "**You're the best at finding solutions.**",
    "**You bring so much joy to others.**",
    "**You're always so respectful to others.**",
    "**You're so dependable and reliable.**",
    "**You're a great friend and confidant.**",
    "**You have an amazing way with words.**",
    "**You're so patient and understanding.**",
    "**You have a great sense of direction.**",
    "**You're an excellent listener.**",
    "**You have such a wonderful outlook on life.**",
    "**You always know how to make people smile.**",
    "**You have an incredible sense of humor.**",
    "**You always brighten up people's days.**",
    "**You're so charming.**",
    "**You make people feel so comfortable.**",
    "**You have such a great presence.**",
    "**You're a truly generous person.**",
    "**You make a real difference in the world.**",
    "**You make life so much more interesting.**",
    "**You're so full of positive energy.**",
    "**You always know how to make people feel appreciated.**",
    "**You have such an open heart.**",
    "**You're a fantastic mentor.**",
    "**You're a true friend to everyone you meet.**",
    "**You're incredibly thoughtful.**",
    "**You're so humble despite your talents.**",
    "**You're always so optimistic.**",
    "**You're such an amazing cook.**",
    "**You have such a great sense of timing.**",
    "**You're a great source of comfort to others.**",
    "**You have a wonderful spirit.**",
    "**You're so strong mentally and emotionally.**",
    "**You're always so generous with your time.**",
    "**You're such a great source of inspiration.**",
    "**You're so full of amazing ideas!**",
    "**You're incredibly good at seeing the bigger picture.**",
    "**You're so kind and respectful to everyone.**",
    "**You're an incredible problem solver.**",
    "**You inspire me to be a better person.**",
    "**You're such a bright and shining star.**",
    "**You always know how to cheer someone up.**",
    "**You're a breath of fresh air.**",
    "**You're so caring, and it shows.**",
    "**You're one of the most positive people I know.**",
    "**You're an amazing listener.**",
    "**You're an absolute gem.**",
    "**You're so understanding and patient.**",
    "**You're always so gracious.**",
    "**You're a wonderful person inside and out.**",
    "**You're always so thoughtful and considerate.**",
    "**You make the world a better place just by being you.**",
    "**You're an absolute treasure.**",
    "**You always put others at ease.**",
    "**You're so brave and fearless.**",
    "**You're a true gem.**",
    "**You're so humble despite your talents.**",
    "**You're a natural born leader.**",
    "**You bring out the best in everyone around you.**",
    "**You're a force for good in the world.**",
    "**You're such a good friend to everyone you meet.**",
    "**You're a true blessing to the people around you.**",
    "**You're so easy to talk to.**",
    "**You're a wonderful and thoughtful person.**",
    "**You're incredibly intelligent.**",
    "**You make every situation better.**",
    "**You're so amazing and unique.**",
    "**You have a heart full of kindness.**",
    "**You are incredibly hard-working.**",
    "**You're always so encouraging and positive.**",
    "**You're truly one of a kind.**",
    "**You're so open-minded and understanding.**",
    "**You're full of great ideas.**",
    "**You're a great listener and advisor.**",
    "**You're always so calm and collected.**",
    "**You're so talented at everything you do.**",
    "**You're a breath of fresh air to everyone around you.**",
    "**You're always so supportive of others.**",
    "**You're always such a pleasure to be around.**",
    "**You're a great role model for everyone around you.**",
    "**You're such an inspiration to everyone.**",
    "**You're the definition of a great friend.**",
    "**You're a positive influence on everyone you meet.**",
    "**You're incredibly creative!**",
    "**You're an incredibly special person.**",
    "**You're amazing in every way.**",
    "**You're the best at what you do.**",
    "**You're truly a blessing to others.**",
    "**You're such a hard worker.**",
    "**You're an absolute ray of sunshine.**",
    "**You're a true example of kindness.**",
    "**You're so full of energy and enthusiasm.**",
    "**You're a great source of inspiration.**",
    "**You're one of the most genuine people I know.**",
    "**You're such a kind and caring person.**",
    "**You're always there when people need you.**",
    "**You inspire others to be the best version of themselves.**",
    "**You're so encouraging and thoughtful.**",
    "**You're so full of positivity.**",
    "**You're a great source of support to others.**",
    "**You're so talented and kind.**",
    "**You're an amazing person inside and out.**",
    "**You're such a positive influence.**",
    "**You're such a joy to be around.**",
    "**You're truly a gift to this world.**",
    "**You're amazing in everything you do.**",
    "**You inspire greatness in others.**",
    "**You're such a wonderful person to be around.**",
    "**You're incredibly strong and resilient.**",
    "**You make everything better just by being there.**",
    "**You're always so thoughtful and kind.**",
    "**You bring happiness wherever you go.**",
    "**You're a great friend and companion.**",
    "**You're a true gift to everyone around you.**",
    "**You're a blessing to everyone you meet.**",
    "**You're a beautiful soul.**",
    "**You're a wonderful person with a big heart.**",
    "**You're such an inspiring individual.**",
    "**You're so full of love and kindness.**",
    "**You're such a bright light in the world.**",
    "**You're an amazing friend and confidant.**",
    "**You're such a rare and special person.**",
    "**You're a truly remarkable individual.**",
    "**You're so thoughtful and considerate.**",
    "**You're so kind-hearted.**",
    "**You are a true blessing to the world.**",
    "**You're an amazing person and friend.**",
    "**You're a shining star in this world.**",
    "**You're so compassionate and caring.**",
    "**You're one of the most wonderful people I've ever met.**",
    "**You're truly an inspiration to everyone you meet.**",
    "**You're always so positive and uplifting.**",
    "**You're such a talented and creative person.**",
    "**You're so intelligent and insightful.**",
    "**You're an amazing listener and friend.**",
    "**You're an incredible person, inside and out.**",
    "**You're a true hero in my eyes.**",
    "**You're such an inspiring person.**",
    "**You're a beautiful person, both inside and out.**",
    "**You're a fantastic person to be around.**",
    "**You're an incredible individual.**",
    "**You're such an amazing and wonderful person.**"
]

    # Choose a random compliment
    compliment = random.choice(compliments)
    await interaction.response.send_message(f"{user.mention}, {compliment}")
    
    
#8BALL COMMAND

@bot.tree.command(name="8ball", description="Ask the Magic 8-Ball a question!")
async def magic_8ball(interaction: discord.Interaction, question: str):
    # List of 8-ball responses
    responses += [
    "Yes, go for it.", "The future looks bright.", "You’ll find your answer soon.",
    "In due time.", "The stars have aligned in your favor.", "Absolutely yes.",
    "It's destined to happen.", "You should pursue it.", "I believe in you.",
    "The cards are in your favor.", "Keep trying, success is near.", "Everything suggests yes.",
    "I’m getting a yes vibe.", "The universe is on your side.", "A favorable outcome is likely.",
    "Yes, but it may take some time.", "Focus and you will succeed.", "I see it happening.",
    "It's all coming together.", "Trust the process.", "The signs are promising.",
    "Ask again in a moment of clarity.", "The answer is within your grasp.", "Yes, in time.",
    "The road ahead looks clear.", "Not in the immediate future.", "Consider it a yes.",
    "There's a strong chance.", "Wait for the right moment.", "The signs point to success.",
    "Something good is coming your way.", "You'll know soon enough.", "It's too soon to say.",
    "It’s a yes for now.", "The outcome looks favorable.", "You’re on the right path.",
    "That’s a positive sign.", "I’m feeling good about this.", "You’re on the verge of success.",
    "Yes, but be cautious.", "It’s happening, just be patient.", "It’s a yes with some conditions.",
    "The cards say yes.", "Absolutely go for it!", "I see a yes, but with challenges ahead.",
    "Everything points to a positive answer.", "Yes, but there may be obstacles.", "I sense success in your future.",
    "It’s a good sign.", "Everything is aligning perfectly.", "The answer lies ahead.",
    "I would say yes, keep pushing forward.", "Yes, but don't rush it.", "The outcome will surprise you.",
    "Yes, but it might take a little longer.", "There’s a good chance this will work out.",
    "It’s leaning towards yes.", "The future is bright for you.", "A strong possibility of success.",
    "Keep your head up, it's a yes!", "Yes, but it’s not going to be easy.", "The universe says yes.",
    "Keep an eye on the signs, it's yes.", "Your instincts are leading you right.", "It’s a yes with a twist.",
    "Yes, but think carefully.", "The answer is in your hands.", "Everything points toward yes.",
    "Yes, but you might need to act quickly.", "Yes, the outcome will be positive.", "I feel confident about this answer.",
    "You’re headed in the right direction.", "Yes, but remain cautious.", "It’s a yes with a side of uncertainty.",
    "Look out for the green light, it's a yes.", "Yes, but wait for a better time.", "Yes, but be patient.",
    "I see a yes, but keep your options open.", "There is definitely a chance this will happen.",
    "I have a positive feeling about this.", "Yes, the signs are all there.", "Success is in the air.",
    "The outcome will be better than expected.", "Yes, but it's not as simple as it seems.",
    "You're on the verge of something great.", "It’s a yes, but with some risk.", "The energy is positive.",
    "I see a yes, but proceed with caution.", "Yes, but be prepared for bumps along the way.",
    "The chances are good, but stay alert.", "Yes, but don’t get ahead of yourself.",
    "The outcome is leaning toward yes.", "I feel a strong yes coming your way.",
    "Yes, just make sure to stay focused.", "There’s a chance for success, but take care.",
    "Yes, but you need to put in the effort.", "Trust your instincts, it's a yes.", "Yes, but don’t rush.",
    "The answer is most likely yes.", "The signs are all pointing to yes.", "Go ahead, it’s a yes.",
    "Yes, but keep your expectations realistic.", "The energy around this is positive.", "I have a strong feeling it's a yes.",
    "Everything is aligning for a yes answer.", "Yes, it’s a good time for this.", "Yes, but you may need to reconsider some things.",
    "The stars suggest yes.", "I see a clear yes on the horizon.", "It’s a yes, but take it slow.",
    "It’s definitely in your favor.", "Yes, but it may not happen instantly.", "Success is almost guaranteed.",
    "It's a yes, but you need patience.", "I see a definite yes coming soon.", "The time is right for a yes.",
    "You're going to get a yes, just wait a little longer.", "A good outcome is on the way.",
    "Yes, but think things through first.", "The future is pointing to yes.", "Yes, just be ready for it.",
    "I see a yes in your future.", "You will succeed, trust the answer.", "It's a yes, but it will require effort.",
    "You're on the right track, it's a yes.", "Yes, but don’t let your guard down.",
    "A yes answer is clear, just wait for it.", "Yes, but don't ignore the obstacles.",
    "The outlook is favorable for a yes.", "Yes, but you need to take action soon.", "Everything looks good for a yes."
]
    
    # Choose a random response
    answer = random.choice(responses)
    
    # Respond to the interaction with the answer in a code block format
    await interaction.response.send_message(f"```{answer}```")
    

# Start the bot (replace YOUR_BOT_TOKEN with your actual bot token)
bot.run("MTMwNzgwMTgxOTA3ODE5NzI5OA.GVzoZ-.LaiE5gsUEBXqilTq6pzg_TAYTUXkyT5sYgcwYY")
